repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.2.1
  hooks:
  - id: dbt-parse
  - id: check-model-has-all-columns
    name: Check columns - core
    files: ^models/staging
  - id: check-model-has-all-columns
    name: Check columns - core
    files: ^models/presentation