name: Deploy dbt Project to PRD

on:
  push:
    branches:
      - main

env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_PRD }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER_PRD }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_PRD }}
  POSTGRES_DATABASE: ${{ vars.POSTGRES_DATABASE_PRD }}
  DBT_SOURCE_SCHEMA: ${{ vars.DBT_SOURCE_SCHEMA_PRD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Run dbt deps
      run: dbt deps

    - name: Run dbt debug
      run: dbt debug --target prd

    - name: Run dbt seed
      run: dbt seed --target prd

    - name: Run dbt run
      run: dbt run --target prd

    - name: Run dbt test
      run: dbt test --target prd