name: Verify project status is ready to promote

on:
  pull_request:
    branches:
      - prd
      - pre

jobs:
  verify_promotion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Run dbt deps
      run: dbt deps

    - name: Create SSL cert files
      env:
        POSTGRES_SSL_CERT: ${{ secrets.POSTGRES_SSL_CERT_PRD }}
        POSTGRES_SSL_KEY: ${{ secrets.POSTGRES_SSL_KEY_PRD }}
        POSTGRES_SSL_ROOT_CERT: ${{ secrets.POSTGRES_SSL_ROOT_CERT_PRD }}
      run: |
        echo "$POSTGRES_SSL_CERT" > /tmp/postgresql.crt
        echo "$POSTGRES_SSL_KEY" > /tmp/postgresql.key
        echo "$POSTGRES_SSL_ROOT_CERT" > /tmp/root.crt
        chmod 0600 /tmp/postgresql.key 

    - name: Run dbt test for target branch
      env:
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_PRD }}
        POSTGRES_USER: ${{ github.head_ref == 'prd' && vars.POSTGRES_USER_PRD || vars.POSTGRES_USER_PRE }}
        POSTGRES_PASSWORD: ${{ github.head_ref == 'prd' && secrets.POSTGRES_PASSWORD_PRD || secrets.POSTGRES_PASSWORD_PRE }}
        POSTGRES_DB: ${{ github.head_ref == 'prd' && vars.POSTGRES_DATABASE_PRD || vars.POSTGRES_DATABASE_PRE }}
        DBT_SOURCE_SCHEMA: ${{ github.head_ref == 'prd' && vars.DBT_SOURCE_SCHEMA_PRD || vars.DBT_SOURCE_SCHEMA_PRE }}
        PGSSLCERT: /tmp/postgresql.crt
        PGSSLKEY: /tmp/postgresql.key
        PGSSLROOTCERT: /tmp/root.crt
      run: dbt test --select tag:promotion --target ${{ github.head_ref }}