name: Refresh seed in project

on:
  workflow_dispatch:

env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST_PRD }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER_PRE }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_PRE }}
  POSTGRES_DB: ${{ vars.POSTGRES_DATABASE_PRE }}
  DBT_SOURCE_SCHEMA: ${{ vars.DBT_SOURCE_SCHEMA_PRE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Run dbt deps
      run: dbt deps

    - name: Run dbt seed
      run: dbt seed --target pre