version: 2

sources:
  - name: jaffle_shop
    schema: |
      {%- if target.name == "prd" -%} landing
      {%- elif target.name == "dev" -%} landing
      {%- else -%} landing
      {%- endif -%}
    tables:
      - name: raw_customers
      - name: raw_items
      - name: raw_orders
      - name: raw_products
      - name: raw_stores
      - name: raw_supplies
      - name: raw_tweets